version: '3.8'

services:
  dynamodb-metrics:
    build:
      context: .
      dockerfile: Dockerfile
    image: dynamodb-metrics:latest
    container_name: dynamodb-metrics-collector
    environment:
      # AWS Configuration
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - AWS_PROFILE=${AWS_PROFILE:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-}
      
      # Application Configuration
      - WAIT_THRESHOLD=${WAIT_THRESHOLD:-1000}
    volumes:
      # Mount AWS credentials (if using profiles)
      - ~/.aws:/home/appuser/.aws:ro
      
      # Mount logs directory for persistence
      - ./logs:/app/logs
      
      # Mount current directory for output
      - .:/app/output
    working_dir: /app
    command: ["--help"]
    
    # Health check
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "get_dynamodb_metrics", "|", "grep", "-v", "grep"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Restart policy
    restart: unless-stopped
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Development service with hot reload (optional)
  dynamodb-metrics-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: dynamodb-metrics:dev
    container_name: dynamodb-metrics-dev
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - AWS_PROFILE=${AWS_PROFILE:-}
    volumes:
      - ~/.aws:/home/appuser/.aws:ro
      - ./logs:/app/logs
      - .:/app/output
      - .:/app/src
    working_dir: /app
    command: ["--help"]
    profiles:
      - dev 